apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: governance
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: ArgoCD Governance and Security project
  sourceRepos:
  - '*'
  destinations:
  - namespace: argocd
    server: https://kubernetes.default.svc
  - namespace: gatekeeper-system
    server: https://kubernetes.default.svc
  - namespace: kube-system
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group : ''
    kind: ''
  namespaceResourceBlacklist:
  - group: ''
    kind: ResourceQuota
  - group: ''
    kind: LimitRange
  - group: ''
    kind: NetworkPolicy
  namespaceResourceWhitelist:
  - group: 'argoproj.io'
    kind: Application
  - group: 'templates.gatekeeper.sh/v1beta1'
    kind: ConstraintTemplate
  - group: 'constraints.gatekeeper.sh/v1beta1'
    kind: '*'