apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    repoURL: {{ .Values.spec.mongodb.source }}
    targetRevision: HEAD
    path: application-manifests/mongodb
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: {{ .Values.namespace }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true