apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policies
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: governance
  source:
    repoURL: {{ .Values.spec.gitops.source }}
    targetRevision: HEAD
    path: opa-policies-manifests
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: gatekeeper-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true