apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opa-gatekeeper
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: controllers
  source:
    repoURL: {{ .Values.spec.gitops.source }}
    targetRevision: HEAD
    path: controller-manifests/opa-gatekeeper
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: gatekeeper-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true